# Imports

In [26]:
import sys
project_dir = 'C:\\Users\\diego\\OneDrive\\Cursos\\Python\\learning_curve'
sys.path.append(project_dir)
import os

from sklearn.base import BaseEstimator, TransformerMixin
from feature_engine.encoding import OrdinalEncoder
import pandas as pd
from datetime import datetime
import numpy as np
import yaml

# Data

In [3]:
teste = pd.read_csv(os.path.join(project_dir,'data/fraudTest.csv'), index_col='Unnamed: 0').reset_index(drop=True)
treino = pd.read_csv(os.path.join(project_dir,'data/fraudTrain.csv'), index_col='Unnamed: 0').reset_index(drop=True)

In [4]:
teste['train_t_split'] = 'TESTE'
treino['train_t_split'] = 'TREINO'

In [5]:
df = pd.concat([teste, treino], ignore_index=True).reset_index(drop=True)

In [6]:
df.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat',
       'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud', 'train_t_split'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1852394 entries, 0 to 1852393
Data columns (total 23 columns):
 #   Column                 Dtype
---  ------                 -----
 0   trans_date_trans_time  object
 1   cc_num                 int64
 2   merchant               object
 3   category               object
 4   amt                    float64
 5   first                  object
 6   last                   object
 7   gender                 object
 8   street                 object
 9   city                   object
 10  state                  object
 11  zip                    int64
 12  lat                    float64
 13  long                   float64
 14  city_pop               int64
 15  job                    object
 16  dob                    object
 17  trans_num              object
 18  unix_time              int64
 19  merch_lat              float64
 20  merch_long             float64
 21  is_fraud               int64
 22  train_t_split          object
dtypes: float64(5), int64(5), object(13)
memory usage: 325.1+ MB

In [8]:
df.head()

  trans_date_trans_time            cc_num                              merchant  ...  merch_long  is_fraud train_t_split
0   2020-06-21 12:14:25  2291163933867244                 fraud_Kirlin and Sons  ...  -81.200714         0         TESTE
1   2020-06-21 12:14:33  3573030041201292                  fraud_Sporer-Keebler  ... -109.960431         0         TESTE
2   2020-06-21 12:14:53  3598215285024754  fraud_Swaniawski, Nitzsche and Welch  ...  -74.196111         0         TESTE
3   2020-06-21 12:15:15  3591919803438423                     fraud_Haley Group  ...  -80.883061         0         TESTE
4   2020-06-21 12:15:17  3526826139003047                 fraud_Johnston-Casper  ...  -85.884734         0         TESTE

[5 rows x 23 columns]

# Simple Prep

In [9]:
class TypesCorrector(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass
    
    def fit(self, X, y=None):
        
        return self
    
    def transform(self, X):
        
        X['trans_date_trans_time'] = pd.to_datetime(X['trans_date_trans_time'])
        
        X['dob'] = pd.to_datetime(X['dob'])
        
        return X

In [10]:
def time_of_day(x):
    if x >= 23 and x < 7:
        return 'Dawn'
    elif x >= 7 and x < 12:
        return 'Morning'
    elif x >= 12 and x < 18:
        return 'Afternoon'
    return 'Evening'

In [11]:
class FeatureCreator(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass
        
        
    def fit(self, X, y=None):
        
        return self
    
    def transform(self, X):
        
        #anomesdia
        X['anomesdia'] = X['trans_date_trans_time'].apply(lambda x: datetime.strftime(x, '%Y%m%d')).astype(int)
        
        #anomes
        X['anomes'] = X['trans_date_trans_time'].apply(lambda x: datetime.strftime(x, '%Y%m')).astype(int)
        
        #Day of week
        X['day_of_week'] = X['trans_date_trans_time'].dt.dayofweek
        
        #Time of day
        X['time_of_day'] = X['trans_date_trans_time'].apply(lambda x: time_of_day(x.hour))
        
        #Client age
        X['client_age'] = np.floor(((X['trans_date_trans_time'] - X['dob']).dt.days/365))
        
        
        X = X.sort_values(by=['cc_num', 'trans_date_trans_time'], ascending=True).reset_index(drop=True)
        
        aux = X.set_index('trans_date_trans_time')
        
        window_size = pd.Timedelta(minutes=30)
        
        X['sum_last_30_minutes'] = aux.groupby('cc_num')['amt'].rolling(window=window_size).sum().reset_index(drop=True)
        
        window_size = pd.Timedelta(hours=1)
        
        X['sum_last_1_hour'] = aux.groupby('cc_num')['amt'].rolling(window=window_size).sum().reset_index(drop=True)
        
        window_size = pd.Timedelta(hours=2)
        
        X['sum_last_2_hour'] = aux.groupby('cc_num')['amt'].rolling(window=window_size).sum().reset_index(drop=True)
        
        window_size = pd.Timedelta(hours=8)
        
        X['sum_last_8_hour'] = aux.groupby('cc_num')['amt'].rolling(window=window_size).sum().reset_index(drop=True)
        
        window_size = pd.Timedelta(hours=12)
        
        X['sum_last_12_hour'] = aux.groupby('cc_num')['amt'].rolling(window=window_size).sum().reset_index(drop=True)
        
        window_size = pd.Timedelta(days=1)
        
        X['sum_last_24_hour'] = aux.groupby('cc_num')['amt'].rolling(window=window_size).sum().reset_index(drop=True)
        
        window_size = pd.Timedelta(days=3)
        
        X['sum_last_72_hour'] = aux.groupby('cc_num')['amt'].rolling(window=window_size).sum().reset_index(drop=True)
        
        return X
        
    def fit_transform(self, X, y=None):
        self.fit(X, y)
        return self.transform(X)

In [12]:
type_corr = TypesCorrector()

In [13]:
df = type_corr.transform(df)

In [14]:
feat_creator = FeatureCreator()

In [15]:
%%time
df = feat_creator.transform(df)

CPU times: total: 56.1 s
Wall time: 1min 7s

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1852394 entries, 0 to 1852393
Data columns (total 35 columns):
 #   Column                 Dtype
---  ------                 -----
 0   trans_date_trans_time  datetime64[ns]
 1   cc_num                 int64
 2   merchant               object
 3   category               object
 4   amt                    float64
 5   first                  object
 6   last                   object
 7   gender                 object
 8   street                 object
 9   city                   object
 10  state                  object
 11  zip                    int64
 12  lat                    float64
 13  long                   float64
 14  city_pop               int64
 15  job                    object
 16  dob                    datetime64[ns]
 17  trans_num              object
 18  unix_time              int64
 19  merch_lat              float64
 20  merch_long             float64
 21  is_fraud               int64
 22  train_t_split          object
 23  anomesdia              int32
 24  anomes                 int32
 25  day_of_week            int32
 26  time_of_day            object
 27  client_age             float64
 28  sum_last_30_minutes    float64
 29  sum_last_1_hour        float64
 30  sum_last_2_hour        float64
 31  sum_last_8_hour        float64
 32  sum_last_12_hour       float64
 33  sum_last_24_hour       float64
 34  sum_last_72_hour       float64
dtypes: datetime64[ns](2), float64(13), int32(3), int64(5), object(12)
memory usage: 473.4+ MB

In [17]:
df.head(10)

  trans_date_trans_time       cc_num  ... sum_last_24_hour sum_last_72_hour
0   2019-01-01 12:47:15  60416207185  ...             7.27             7.27
1   2019-01-02 08:44:57  60416207185  ...            60.21            60.21
2   2019-01-02 08:47:36  60416207185  ...           142.29           142.29
3   2019-01-02 12:38:14  60416207185  ...           177.08           177.08
4   2019-01-02 13:10:46  60416207185  ...           196.99           204.26
5   2019-01-03 13:56:35  60416207185  ...             6.87           211.13
6   2019-01-03 17:05:10  60416207185  ...            15.30           219.56
7   2019-01-04 13:59:55  60416207185  ...           125.54           329.40
8   2019-01-04 21:17:22  60416207185  ...           143.85           356.14
9   2019-01-05 00:42:24  60416207185  ...           249.05           461.34

[10 rows x 35 columns]

In [17]:
df.is_fraud.mean()

0.005210014716091717

# Encoding

In [27]:
features = yaml.safe_load(open(os.path.join(project_dir, 'src', 'feature', 'config', 'variaveis.yaml'), 'rb'))

In [28]:
colunas_enc = list(set(df.select_dtypes(include=['object', 'string']).columns.tolist()) & set(features['descritivas']))

In [32]:
ordEnc = OrdinalEncoder(variables = colunas_enc, encoding_method='arbitrary')

In [33]:
df = ordEnc.fit_transform(df)

In [34]:
df.head()

  trans_date_trans_time       cc_num  ... sum_last_24_hour  sum_last_72_hour
0   2019-01-01 12:47:15  60416207185  ...             7.27              7.27
1   2019-01-02 08:44:57  60416207185  ...            60.21             60.21
2   2019-01-02 08:47:36  60416207185  ...           142.29            142.29
3   2019-01-02 12:38:14  60416207185  ...           177.08            177.08
4   2019-01-02 13:10:46  60416207185  ...           196.99            204.26

[5 rows x 35 columns]

In [35]:
df[df.train_t_split == 'TREINO'].to_parquet(os.path.join(project_dir, 'data', 'feat', 'treino.parquet.gzip'), compression='gzip', index=False)

In [36]:
df[df.train_t_split == 'TESTE'].to_parquet(os.path.join(project_dir, 'data', 'feat', 'teste.parquet.gzip'), compression='gzip', index=False)